import streamlit as st
import yfinance as yf
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

# UI Configuration
st.set_page_config(page_title="ML Trading Signal Predictor", layout="wide")
st.title("📈 ML Algorithmic Trading Predictor")
st.write("This app uses a Random Forest Classifier to predict if a stock will close UP or DOWN tomorrow based on historical momentum.")

# Sidebar parameters
st.sidebar.header("Model Parameters")
ticker = st.sidebar.text_input("Stock Ticker (e.g., AAPL, RELIANCE.NS)", "AAPL")
years = st.sidebar.slider("Years of Historical Data", 1, 10, 5)

@st.cache_data 
def load_data(ticker, years):
    url = "https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv"
    df = pd.read_csv(url, parse_dates=['Date'], index_col='Date')
    df = df.rename(columns={'AAPL.Close': 'Close', 'AAPL.Volume': 'Volume'})
    return df

data = load_data(ticker, years)
st.subheader(f"Historical Data (Safe Mode: AAPL Dataset Override)")
st.line_chart(data['Close'])

# Engineer momentum indicators
df = data.copy()
df['SMA_10'] = df['Close'].rolling(window=10).mean() # Short-term momentum
df['SMA_50'] = df['Close'].rolling(window=50).mean() # Long-term baseline
df['Daily_Return'] = df['Close'].pct_change()

# Define binary target: 1 if next close > current close,else 0
df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)

# Clean NaN values generated by rolling windows
df = df.dropna()

# Define feature set and target variable
features = ['SMA_10', 'SMA_50', 'Daily_Return', 'Volume']
X = df[features]
y = df['Target']

# Time-series split (shuffle=False is strictly required to prevent forward-looking data leakage)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)

# Train Random Forest (chosen to mitigate overfitting common in financial time-series data)
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
model.fit(X_train, y_train)

# Generate test predictions and evaluation metrics
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions)

st.subheader("🤖 Model Evaluation Metrics")
col1, col2 = st.columns(2)
col1.metric("Model Accuracy", f"{accuracy * 100:.2f}%")
col2.metric("Model Precision", f"{precision * 100:.2f}%")

st.write("**Note:** In algorithmic trading, an accuracy consistently above 51-53% is generally considered profitable.")

# Predict Tomorrow's Move
# We use .tail(1) to keep it as a DataFrame so the model sees the feature names
latest_row = X.tail(1) 
tomorrow_pred = model.predict(latest_row)

st.subheader("🔮 Tomorrow's Prediction")
if tomorrow_pred[0] == 1:
    st.success(f"The model predicts the stock will close **HIGHER** tomorrow.")
else:
    st.error(f"The model predicts the stock will close **LOWER** tomorrow.")